package ua.waldemar.customdi.api.error

object ApiErrorCodes {
    const val UNKNOWN_ERROR = "UNKNOWN_ERROR"
    const val CONNECTION_FAILURE = "CONNECTION_FAILURE"
    const val REFRESH_AUTH_FAILURE = "REFRESH_AUTH_FAILURE"
    const val TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"

    const val TOKEN_IS_NOT_VALID = "TOKEN_IS_NOT_VALID"
    const val TOKEN_IS_BLOCKED = "TOKEN_IS_BLOCKED"
    const val INVALID_PK_TOKEN = "INVALID_PK_TOKEN"
    const val TOKEN_INVALIDATED = "TOKEN_INVALIDATED"
    const val EXTRA_APPROVE_EXPIRED = "EXTRA_APPROVE_EXPIRED"
    const val EXTRA_APPROVE_RESET = "EXTRA_APPROVE_RESET"
    const val EXTRA_APPROVE_RESULT_ERROR = "EXTRA_APPROVE_RESULT_ERROR"

    const val RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    const val USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    const val EMPLOYER_NOT_ACTIVE = "EMPLOYER_NOT_ACTIVE"
    const val EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    const val BANK_NOT_APPROVED = "BANK_NOT_APPROVED"
    const val USER_NOT_CONSENTED = "USER_IS_NOT_CONSENTED"
    const val USER_FLOWS_NOT_FOUND = "USER_FLOWS_NOT_FOUND"
    const val APPLICATION_VERSION_NOT_SUPPORTED = "APPLICATION_VERSION_NOT_SUPPORTED"
}